{% set version = "0.3.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-feather
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/feather_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/feather/feather_{{ version }}.tar.gz
  sha256: 4abbb69da7a937825d362008355ab8f233779a3110217d0c01064bff7ca54853

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-hms
    - r-tibble
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp
    - r-hms
    - r-tibble

test:
  commands:
    - $R -e "library('feather')"           # [not win]
    - "\"%R%\" -e \"library('feather')\""  # [win]

about:
  home: https://github.com/wesm/feather
  license: Apache 2.0
  summary: Read and write feather files, a lightweight binary columnar data store designed for
    maximum speed.
  license_family: APACHE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: feather
# Title: R Bindings to the Feather 'API'
# Version: 0.3.2
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", role = c("aut", "cre")), person("RStudio", role = "cph"), person("Feather developers", role = "ctb", comment = "Bundled feather library"), person("Google", role = "ctb", comment = "Bundled flatbuffers code"), person("LevelDB Authors", role = "ctb") )
# Description: Read and write feather files, a lightweight binary columnar data store designed for maximum speed.
# Encoding: UTF-8
# License: Apache License 2.0
# LazyData: true
# URL: https://github.com/wesm/feather
# BugReports: https://github.com/wesm/feather/issues
# LinkingTo: Rcpp
# Imports: Rcpp, tibble, hms
# Suggests: testthat, dplyr
# SystemRequirements: little-endian platform
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-01-07 14:30:33 UTC; hadley
# Author: Hadley Wickham [aut, cre], RStudio [cph], Feather developers [ctb] (Bundled feather library), Google [ctb] (Bundled flatbuffers code), LevelDB Authors [ctb]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-01-07 21:20:03 UTC
