appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: WJch/+xL9gka1o28L7+vebNK5GSgJeA9d/Q88cOKPEUSCKhMYA3XwvdMjRLLnb7Q/l7wk5zQTL9KXZBYen7N5HuWnNXME6Sm3kr73Ouk8j66SzcVSzKTBzxzwScfleLfCZeTPThqazYv22+Bl6S0zjSYlyMd14dDMZ6o0I4w6IcI7tW+wkf3+JDeLtb5w9obcS2bzpVLOs8blLjFQFbL0vtIPZ6uCboG7iEGO2j9T8MZGT3Z3weXZsYhFwikZyMt4kBBXTHlltB54emjmk7xjZW0r4R74FqwDS322q3w6Zkr6PmgQiwqXY2gI4keMSj/4kaO6cAjl2bzfveM6n5GzkxLe2rlrlA4gdQY0XjVn1kFhFuExfuUvk480/t2WmfHMBwSPyS1dpxTd3Ak75SN2vr6bIYHm6onf5f0i/nPDIE0P/gQSSF9B8SnBE4oix+sEsJNJ0R188MKkPXDbhSpYrOuanh83gf2Q7+sgsvkMdrx4O2kmgDVMm5+4lWJKSFbDkzLp+Vh5jRz8F0gNQG64Jj2tCbN7uyKdHYeV1n+n8Y0IGk6yPkpV5Z6czOykYDq9I2xwPsgN4kwxYvEwHNVfkWNRN8sMDxtIDp+hN5aoTrMK64CJsK/nAnxf4M3AjGg4ungoRQL4iWXPSzqCKPdK5LwrV7yBq9+RO0nUGCZOWI=
